<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.open.coffee</groupId>
	<artifactId>coffee</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<modules>	
		<module>parent</module>
		
		<module>common-jars/common</module>
		<module>common-jars/aviator</module>	
		
		<module>study/designpattern</module>
				
		<module>study/jwt</module>
		<module>study/mybatisg</module>

		<module>study/web</module>
		<module>study/https</module>
		<module>study/websocket</module>
		
		<module>study/k8s</module>
		<module>study/k8sclient</module>
		<module>study/harbor</module>
		
		
		<module>study/logtool</module>
		<module>study/compiler</module>
		
		<module>study/license</module>
		
		<module>study/redis</module>
		
		<module>study/qrcode</module>
	</modules>
</project>